language: java
jdk:
 - openjdk8
  
cache:
  directories:
  - '$HOME/.m2/repository'
  
script:
  - mvn clean package -DskipTests=true

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 7911f794-5a9b-4db4-80cc-1c2acad50fa8