#web容器配置
server:
  context-path: /
  port: 8080
#定义环境引用的配置文件
spring:
  application:
    name: super-boot-operation-center
    index: ${random.int}
  http:
    encoding:
      force: true
      charset: UTF-8
    multipart:
      enabled: true
      max-file-size: 1024MB
  #热加载配置
  devtools:
    remote:
      secret: thisismysecret
  cloud:
    #启用消息追踪
    bus:
      trace:
        enabled: true
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
  #配置消息总线
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  #启用安全配置
  security:
    basic:
      enabled: true
    user:
      name: superboot #用户名
      password: superboot #密码
  redis:
    cluster:
      nodes: 127.0.0.1:7000, 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005
      pool:
        max-active: 10
        max-wait: 10000
        max-idle: 20
        min-idle: 5
      cache-expire: 1800
      timeout: 10000
#关闭安全认证
management:
  security:
    enabled: false
#启用调试模式
debug: true
#日志配置
logging:
  config: classpath:log4j2-dev.xml
eureka:
  instance:
    #心跳时间间隔
    lease-renewal-interval-in-seconds: 10
    #无心跳多久后,该服务失效
    lease-expiration-duration-in-seconds: 30
    appname: 监控中心